### ISSUE TITLE
Double tapping skills shows description, and removes and adds the skill just removed

### ISSUE THREAD

**Issue by CrushyGreenRen** [r-paydaybuilds/pd2builder#4]
I decided to try the new mobile version and tried to degrade a skill from Ace to Basic, successfully degrading it but after a very short while, Ace was applied again.

This also goes to removing basic skills, but not giving basic skills.

**Comment by DocCobra** [comment]
Thanks for the report! This should be resolved in next version, where long press should open the skill description.

**Comment by ImUrX** [comment]
this is sadly still bugged because of me in b284a3a so im keeping it open until i fix it.

**Comment by ImUrX** [comment]
fixed in 2faed9f
