### ISSUE TITLE
Copycat Perk Deck is missing

### ISSUE THREAD

**Issue by 11BelowStudio** [r-paydaybuilds/pd2builder#57]
(in it's own issue because it's a complicated one).

Copycat perk deck is currently missing. Need to work out how to handle the 'pick a boost' gimmick on here, which could be a bit of a pain in the arse to get working (as well as allowing the perk deck-specific throwables to work with Copycat)

**Comment by ImUrX** [comment]
Being done in ``copycat`` branch

**Comment by 11BelowStudio** [comment]
it's added now :)
